main: net.dmg2.LevelPlayerStats.LevelPlayerStats
name: LevelPlayerStats
version: Beta 1.0

permissions:
    LevelPlayerStats.self:
        description: Allows to use plugin.
        default: true

commands:
   lps:
      description: Main command
      permission: LevelPlayerStats.self
      usage: /lps