main: net.dmg2.ChangeSign.ChangeSign
name: ChangeSign
version: 1.0

permissions:
    ChangeSign.self:
        description: Allows to use plugin.
        default: op

commands:
   sign:
      description: Main command
      permission: ChangeSign.self
      usage: |
          /sign (line # [1-4]) (text) - Updates line's text on the sign